SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (SELECT MAX(X.FAVORITES)
                  FROM REST_INFO X
                  GROUP BY X.FOOD_tYPE)
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC