SELECT TITLE, U.BOARD_ID, REPLY_ID, R.WRITER_ID, R.CONTENTS, 
DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") CREATED_DATE
FROM USED_GOODS_BOARD U, USED_GOODS_REPLY R
WHERE U.BOARD_ID = R.BOARD_ID
AND U.CREATED_DATE LIKE "2022-10%"
ORDER BY R.CREATED_DATE, TITLE